version: "3.9"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abcd12345
      POSTGRES_DB: stickers_exchanger
      
  stickers_exchanger:
    image: stickers_exchanger:1.0.0
    ports:
      - "8080:8080"
    environment:
      API_HOST: 0.0.0.0
      API_PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: abcd12345
      DB_NAME: stickers_exchanger
      DB_MIGRATE: false
      COOKIE_DOMAIN: localhost